#ADS1256:
#  init: None

#TCA9555:
#  init:
#    address: 0x20

#IrradDAQBoard:
#  init:
#    version: v0.2
#    address: 0x20

ZaberXYStage:
  init:
    serial_port: /dev/ttyUSB0

ArduinoTempSens:
  init:
    port: /dev/ttyUSB1
    baudrate: 115200
    timeout: 5
    ntc_lim: (-55, 125)