#ADS1256:
#  init: None

#TCA9555:
#  init:
#    address: 0x20

ADCBoard:
  init: None

IrradDAQBoard:
  init:
    version: v0.2
    address: 0x20

ScanStage:
  init:
    port: /dev/ttyUSB1
    config: ./motorstage/scan_stage.yaml

SetupTableStage:
  init:
    port: /dev/ttyUSB1
    config: ./motorstage/setup_table_stage.yaml

ExternalCupStage:
  init:
    host: None
    port: 1234
    udp:
      - 1
      - 2
    config: ./motorstage/external_cup_stage.yaml

ArduinoTempSens:
  init:
    port: /dev/ttyUSB0
    baudrate: 115200
    timeout: 5
    ntc_lim:
      - -55
      - 125