#ADS1256:
#  init: None

#TCA9555:
#  init:
#    address: 0x20

ADCBoard:
  init: None

IrradDAQBoard:
  init:
    version: v0.2
    address: 0x20

ScanStage:
  init:
    config: ./motorstage/scan_stage.yaml
    port: /dev/ttyUSB1
    n_axis: 2
    axis_addrs:
      - 1
      - 2
    invert_axis:
      - 1
    axis_init:
      - step: 0.1953125e-6
        travel: 300.0e-3
        model: LRQ300HL-E01T3A
      - step: 0.1953125e-6
        travel: 300.0e-3
        model: LRQ300HL-E01T3A

SetupTableStage:
  init:
    config: ./motorstage/setup_table_stage.yaml
    port: /dev/ttyUSB1
    step: 0.1953125e-6
    travel: 300.0e-3
    model: LRQ300HL-E01T3A

ExternalCupStage:
  init:
    config: ./motorstage/external_cup_stage.yaml
    host: None
    port: 1234
    udp:
      - 1
      - 2
    travel: 716.5e-3
    model: ITEM-Linear-Stage

ArduinoTempSens:
  init:
    port: /dev/ttyUSB0
    baudrate: 115200
    timeout: 5
    ntc_lim:
      - -55
      - 125