### Base configuration of a one dimensional motorstage axis
# Meta data
meta: none
last_updated: none
filename: none
# Axis is inverted
inverted: False
# Physical properties of axis
speed:  # Speed with which axis moves
  value: null
  unit: null
range:  # Movement range of axis
  value: null
  unit: null
accel:  # Acceleration with which *speed* is approached
  value: null
  unit: null
travel: # Total travel of axis
  value: 0
  unit: m
position:  # Current location on axis
  value: null
  unit: null
positions:  # Positions known to axis
  {}