### Base configuration of a one dimensional motorstage axis
# Meta data
meta: none
last_updated: none
filename: none
# Physical properties of axis
speed:  # Speed with which axis moves
  value: none
  unit: none
range:  # Movement range of axis
  value: none
  unit: none
accel:  # Acceleration with which *speed* is approached
  value: none
  unit: none
travel: # Total travel of axis
  value: 0
  unit: m
position:  # Current location on axis
  value: none
  unit: none
positions:  # Positions known to axis
  {}