### This config file contains all information relevant to data acquisition (DAQ) ###

# Configuration of available DAQ devices aka secondary electron monitors (SEM)
sem:
  default: SEM-15-deg
  all:
    - SEM-39-deg
    - SEM-15-deg

# Proportionality constant(s) of the SEMs for online measurements of the HISKP proton beam current.
# The beam current I_Beam is calculated by the SEM sum signal U_SEM in [V], the 5V full-scale scale I_fs
# of the custom readout electronics (3.3,10,33,100,330,1000) in [nA] and the proportionality constant lambda in [1/V] like:
# I_Beam(U_SEM) = lambda * I_fs * U_SEM
lambda:
  default: lambda_1
  all:
    lambda_1:
      nominal: 0.937
      sigma: 0.009
      hv_sem: 100 V
      unit: 1/V
      device: SEM-15-deg
      particle: proton
      energy: 14 MeV
      date: Wed Feb 23 14:00:00 2022


# Proton hardness factors
kappa:
  default: kappa_1
  all:
    kappa_1:
      nominal: 4.1
      sigma: 0.6
      energy: 12.26
      date: Wed Jul 15 13:30:00 2020