0:  # x axis
  speed: # Speed with which axis moves
    value: none
    unit: none
  range: # Movement range of axis
    value: none
    unit: none
  accel: # Acceleration with which *speed* is approached
    value: none
    unit: none
  travel: # Total travel of axis
    value: 0
    unit: m
  position: # Current location on axis
    value: none
    unit: none
  positions: # Positions known to axis
    { }
1:  # y axis
  speed: # Speed with which axis moves
    value: none
    unit: none
    range: # Movement range of axis
      value: none
      unit: none
    accel: # Acceleration with which *speed* is approached
      value: none
      unit: none
    travel: # Total travel of axis
      value: 0
      unit: m
    position: # Current location on axis
      value: none
      unit: none
    positions: # Positions known to axis
      { }
last_update: 0
maintenance_interval: 500000
meta: Maintenance interval is every 500 km. See https://www.zaber.com/wiki/Manuals/X-LRQ-E#Precautions
