log:
  level: INFO
  file: /home/leloup/log_file_irrad.txt
tcp:
  ip:
#    server: 131.220.162.129
#    host: 131.220.167.206
    server: localhost
    host: localhost
  port:
    log: 5100
    raw_data: 5200
    interpreter: 5300
    stage: 5400
    adc: 5500
    server: 5600
daq:
  SEM_C:
    channels:
      - L
      - R
      - U
      - D
      - SUM
      - RULE_H
      - RULE_V
    types:
      - sem_left
      - sem_right
      - sem_up
      - sem_down
      - sem_sum
      - sem_h_shift
      - sem_v_shift
    sampling_rate: 30000
    ro_scale: 330